from fastapi import FastAPI, HTTPException
import httpx

app = FastAPI(
    title="LexGuard AI - Orchestrator",
    version="1.0.0"
)

RETRIEVAL_AGENT_URL = "http://127.0.0.1:8002"
VERIFICATION_AGENT_URL = "http://127.0.0.1:8004"


@app.get("/health")
def health_check():
    return {
        "service": "orchestrator",
        "status": "healthy"
    }


@app.post("/ask")
async def ask_question(request: dict):
    query = request.get("query")

    if not query:
        raise HTTPException(
            status_code=400,
            detail="Query is required"
        )

    async with httpx.AsyncClient() as client:

        # --------------------------------------------------
        # 1. Retrieve legal evidence
        # --------------------------------------------------
        retrieval_response = await client.post(
            f"{RETRIEVAL_AGENT_URL}/process",
            json={
                "query": query,
                "legal_area": "employment",
                "keywords": query.split()
            }
        )

        if retrieval_response.status_code != 200:
            raise HTTPException(
                status_code=502,
                detail="Retrieval Agent failed"
            )

        retrieval_data = retrieval_response.json()

        documents = retrieval_data["documents"]

        # --------------------------------------------------
        # 2. Temporary explanation output
        # --------------------------------------------------
        # The real Explanation Agent will replace this later.
        answer = (
            "This is a temporary test answer generated by the "
            "orchestrator. The final answer will come from the "
            "Explanation Agent."
        )

        citations = []

        if documents:
            citations.append(
                {
                    "document_id": documents[0]["document_id"],
                    "passage": documents[0]["passage"]
                }
            )

        # --------------------------------------------------
        # 3. Verify the answer and citations
        # --------------------------------------------------
        verification_response = await client.post(
            f"{VERIFICATION_AGENT_URL}/verify",
            json={
                "query": query,
                "answer": answer,
                "citations": citations,
                "retrieved_documents": documents
            }
        )

        if verification_response.status_code != 200:
            raise HTTPException(
                status_code=502,
                detail="Verification Agent failed"
            )

        verification_data = verification_response.json()

        # --------------------------------------------------
        # 4. Return final result
        # --------------------------------------------------
        return verification_data
